apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: helpdesk

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgres-container
          image: postgres:18
          ports:
            - containerPort: 5432

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

          volumeMounts:
            - name: postgres-initdb
              mountPath: /docker-entrypoint-initdb.d

          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

      volumes:
        - name: postgres-initdb
          configMap:
            name: postgres-initdb
